### ISSUE TITLE
Balancer's conservation function does not diverge to Uniswap's

### ISSUE THREAD

**Issue by krotkiewicz** [xujiahuayz/bondingcurves#15]
For w1=w2=0.5 the functions are different.

![image](https://user-images.githubusercontent.com/2101767/158040828-6aca5fd1-7275-40a6-ad67-0527c1f3a9e0.png)

Earlier in the paper it is stated that 

> Balancer can also be deemed a generalization of Uniswap; the latter is a special case of the former with w1 = w2 = 1/2 

and this can be found in the code that Uniswap AMM is just Balancer with w1=w2=0.5.

Probably I have missied something, would love to hear an explanation for that. Thank you.

**Comment by xujiahuayz** [comment]
Plug w1=w2=0.5 Into Balancer’s conservation function (2-asset scenario) and you get

C^2=r1 * r2

Which is the form of uniswap v2 conservation function (where the product of two reserve quantities stays constant)
